#!/bin/bash
set -e
# build 1-beta

# the directory of the current script
dir=$(pwd)
# -----------------------
# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color
# -----------------------


printf "${GREEN} Welcome! ${NC}\n"

git checkout develop

echo "Incrementing versionCode >>"

printf "The old version was :${RED} `grep -a versionCode  $dir/app/build.gradle` ${NC} \n" 

perl -i -pe 's/versionCode \K(\d+)/ $1+1 /e' $dir/app/build.gradle
# perl -i -pe 's/versionCode \K(\d+)/ $1+1 /e' file1.txt

printf "The new version is :${GREEN}`grep -a versionCode  $dir/app/build.gradle` ${NC} \n"

echo "Building the app >>"

# building app
./gradlew assembleRelease

echo "APP GENERATED SUCCESSFULY"
echo "Commiting and pushing to git repo"
git add .
git commit -m "Bumping versioncode to `grep -a versionCode  $dir/app/build.gradle`"
git push origin develop

echo "SENDING MAIL "

(echo "fdsfsf" ; uuencode app/build/outputs/apk/app-release.apk app/build/outputs/apk/app-release.apk) | mail -s "Test from terminal" m.zakaria.elzoghbi@gmail.com  


echo "end----->"
