#!/bin/bash
set -e
# build 1-beta

# the directory of the current script
dir=$(pwd)
# -----------------------
# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color
# -----------------------


printf "${GREEN} Welcome! ${NC}\n"

git checkout develop

echo "Incrementing versionCode >>"

printf "The old version was :${RED} `grep -a versionCode  $dir/app/build.gradle` ${NC} \n" 

perl -i -pe 's/versionCode \K(\d+)/ $1+1 /e' $dir/app/build.gradle
# perl -i -pe 's/versionCode \K(\d+)/ $1+1 /e' file1.txt

printf "The new version is :${GREEN}`grep -a versionCode  $dir/app/build.gradle` ${NC} \n"

echo "Building the app >>"

# building app
./gradlew assembleRelease

echo "APP GENERATED SUCCESSFULY"
echo "Commiting and pushing to git repo"
git add .
versionNo=$(perl -nle 'print $1 if /versionCode.*?(\d+)/' $dir/app/build.gradle)
git commit -m "Bumping the version to `grep -a versionName  $dir/app/build.gradle`-$versionNo"
git push origin develop

echo "SENDING E-MAIL"

# sending email with body and attaching the release version
(echo "This will be the body of the mail" ; uuencode app/build/outputs/apk/app-release.apk app/build/outputs/apk/app-release.apk) | mail -s "This is the e-mail subject" m.zakaria.elzoghbi@gmail.com  


echo "end----->"
